"""create_user_skills

Revision ID: 0008_create_user_skills
Revises: 0007_create_evaluations
Create Date: 2026-09-30 08:26:17.909310
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0008_create_user_skills'
down_revision: Union[str, Sequence[str], None] = '0007_create_evaluations'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_skills',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('successful_attempts', sa.Integer(), nullable=False),
    sa.Column('initial_score', sa.Integer(), nullable=False),
    sa.Column('initial_assessment_id', sa.Integer(), nullable=True),
    sa.Column('mass', sa.Numeric(), nullable=False),
    sa.Column('residual_sum', sa.Numeric(), nullable=False),
    sa.Column('squared_residual_sum', sa.Numeric(), nullable=False),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mass > 0 AND mass < 'Infinity'::numeric AND residual_sum BETWEEN -mass AND mass AND squared_residual_sum BETWEEN 0 AND mass", name='ck_user_skills_totals'),
    sa.CheckConstraint('attempts > 0 AND successful_attempts BETWEEN 0 AND attempts', name='ck_user_skills_counts'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 0.95', name='ck_user_skills_confidence'),
    sa.CheckConstraint('initial_assessment_id IS NOT NULL OR initial_score = 500', name='ck_user_skills_initial'),
    sa.CheckConstraint('score BETWEEN 0 AND 1000 AND initial_score BETWEEN 0 AND 1000', name='ck_user_skills_scores'),
    sa.ForeignKeyConstraint(['initial_assessment_id', 'skill_id'], ['assessment_results.assessment_id', 'assessment_results.skill_id'], name='fk_user_skills_initial_result', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name='fk_user_skills_skill', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_skills_user', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_user_skills_user_skill')
    )
    op.create_index('ix_user_skills_initial_result', 'user_skills', ['initial_assessment_id', 'skill_id'], unique=False)
    op.create_index('ix_user_skills_skill', 'user_skills', ['skill_id'], unique=False)
    op.create_table('skill_evidence',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('policy_version', sa.String(length=30), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('before_state', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(applied AND before_state IS NOT NULL AND after_state IS NOT NULL AND jsonb_typeof(before_state) = 'object' AND jsonb_typeof(after_state) = 'object') OR (NOT applied AND before_state IS NULL AND after_state IS NULL)", name='ck_skill_evidence_states'),
    sa.CheckConstraint("policy_version = 'manual-skill-v1'", name='ck_skill_evidence_policy'),
    sa.ForeignKeyConstraint(['evaluation_id', 'skill_id'], ['attempt_evaluation_skills.evaluation_id', 'attempt_evaluation_skills.skill_id'], name='fk_skill_evidence_result', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name='fk_skill_evidence_skill', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_skill_evidence_user', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id', 'skill_id', name='uq_skill_evidence_evaluation_skill')
    )
    op.create_index('ix_skill_evidence_skill', 'skill_evidence', ['skill_id'], unique=False)
    op.create_index('ix_skill_evidence_user_skill_order', 'skill_evidence', ['user_id', 'skill_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_skill_evidence_user_skill_order', table_name='skill_evidence')
    op.drop_index('ix_skill_evidence_skill', table_name='skill_evidence')
    op.drop_table('skill_evidence')
    op.drop_index('ix_user_skills_skill', table_name='user_skills')
    op.drop_index('ix_user_skills_initial_result', table_name='user_skills')
    op.drop_table('user_skills')
    # ### end Alembic commands ###
