import { test, expect, login, noOverflow } from './helpers'

test('ciclo real: tentativa, revisão e progresso do dono', async ({ page, request }, testInfo) => {
  if (process.env.CODETRACK_QA_DISPOSABLE !== '1' || !process.env.QA_PASSWORD) throw new Error('Execute a jornada real pelo harness Python descartável.')
  const password = process.env.QA_PASSWORD
  const challengeId = Number(process.env.QA_CHALLENGE_ID)
  const skillId = Number(process.env.QA_SKILL_ID)
  expect(Number.isSafeInteger(challengeId) && challengeId > 0).toBe(true)
  const api = 'http://127.0.0.1:8100/api/v1'
  const auth = await request.post(`${api}/auth/login`, { data: { email: 'reviewer@qa.example', password } })
  expect(auth.status()).toBe(200)
  const headers = { Authorization: 'Bearer ' + (await auth.json()).access_token }
  page.on('dialog', dialog => dialog.accept())
  await page.goto('/'); await login(page, 'owner@qa.example', password)
  await page.getByLabel('Área de interesse').selectOption({ label: 'Programming' })
  await page.getByRole('radio', { name: 'Python', exact: true }).check()
  await page.getByRole('button', { name: 'Ver desafio: First practice' }).click()
  await page.getByRole('button', { name: 'Iniciar ou retomar tentativa' }).click()
  const editor = page.getByLabel('Resposta em texto ou código')
  await expect(editor).toHaveValue('')
  const attemptId = Number(page.url().split('/').pop())
  const answer = '  print(1 + 1)\nA soma é 2. 😀  '
  await editor.fill(answer); await page.getByRole('button', { name: 'Salvar rascunho' }).click()
  await expect(page.getByText('Rascunho salvo.', { exact: true })).toBeVisible()
  const changed = await request.patch(`${api}/challenges/${challengeId}`, { headers, data: { title: 'Changed catalog title', is_active: false } })
  expect(changed.status()).toBe(200)
  await page.getByRole('link', { name: 'Voltar às tentativas' }).click()
  await page.getByRole('link', { name: 'Retomar: First practice' }).click()
  await expect(editor).toHaveValue(answer)
  await page.reload(); await login(page, 'owner@qa.example', password)
  await expect(editor).toHaveValue(answer)
  await page.getByRole('button', { name: 'Enviar para revisão' }).click()
  await expect(page.getByText('Sua resposta aguarda revisão manual', { exact: false })).toBeVisible()
  await expect(editor).toHaveCount(0)
  const evaluation = await request.post(`${api}/reviews/attempts/${attemptId}/evaluation`, { headers, data: {
    feedback: 'Adição explicada com clareza. <b>Texto literal</b>',
    skills: [{ skill_id: skillId, classification: 'MET', justification: 'A resposta demonstra soma e resultado.' }],
  } })
  expect(evaluation.status()).toBe(201)
  await page.getByRole('button', { name: 'Atualizar avaliação' }).click()
  await expect(page.getByRole('heading', { name: 'Feedback geral' })).toBeVisible()
  await expect(page.locator('.evaluation-skills')).toContainText('Atendido')
  await expect(page.locator('main b')).toHaveCount(0)
  await page.locator('.attempt-evaluation').scrollIntoViewIfNeeded(); await noOverflow(page)
  await page.screenshot({ path: testInfo.outputPath('desktop.png') })
  await page.setViewportSize({ width: 390, height: 844 }); await noOverflow(page)
  await page.screenshot({ path: testInfo.outputPath('mobile.png') })
  await page.getByRole('link', { name: 'Voltar ao painel', exact: true }).click()
  await expect(page.locator('.skill-progress-list')).toContainText('504')
  await page.getByLabel('Área de interesse').selectOption({ label: 'Programming' })
  await page.getByRole('radio', { name: 'Python', exact: true }).check()
  await expect(page.getByText('Não há atividades elegíveis', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Sair', exact: true }).click(); await login(page, 'other@qa.example', password)
  await page.getByRole('link', { name: 'Tentativas', exact: true }).click()
  await expect(page.getByText('Você ainda não iniciou uma tentativa.')).toBeVisible()
  await page.goto(`/tentativas/${attemptId}`); await login(page, 'other@qa.example', password)
  await expect(page.getByRole('alert')).toContainText('Tentativa não encontrada')
  await expect(page.locator('.attempt-evaluation')).toHaveCount(0)
  await expect(page).toHaveTitle('CodeTrack')
})
